// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jpccgmkcmvbbousvpjpw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpwY2NnbWtjbXZiYm91c3ZwanB3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0MTkwOTcsImV4cCI6MjA1ODk5NTA5N30.nmc9zjVnc-zbFTx2PQU59C57QjXoTMy_McO54eBuhco";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);